### ISSUE TITLE
2 GPU tests fail

### ISSUE THREAD

**Issue by otaj** [facebookresearch/faiss#1395]
# Summary

Hi,
first of all, sorry for such a host of issues today, I promise it's the last one today :)

However, two GPU tests fail for me.
The tests are
* `TestGpuMemoryException.AddException`
* `TestGpuIndexIVFPQ.Float16Coarse`

# Platform

Arch Linux

GCC 10.2.0
CUDA 11.0.3
GCC used for NVCC 9.3.0
GPU card Quadro T1000 (4GB)

Faiss version: commit 9873376d8c5b4885afa77b09cec982fd59cb5486

Faiss compilation options: `-DFAISS_ENABLE_GPU=ON -DFAISS_ENABLE_PYTHON=ON -DCUDAToolkit_ROOT=/opt/cuda -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CUDA_ARCHITECTURES=\"75\"`

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Test log
```
Running tests...
Test project /home/otaj/files/aur/faiss-cuda-git/src/faiss/build
        Start   1: BinaryFlat.accuracy
  1/109 Test   #1: BinaryFlat.accuracy ...........................   Passed    0.01 sec
        Start   2: TestIvlistDealloc.IVFFlat
  2/109 Test   #2: TestIvlistDealloc.IVFFlat .....................   Passed    0.10 sec
        Start   3: TestIvlistDealloc.IVFSQ
  3/109 Test   #3: TestIvlistDealloc.IVFSQ .......................   Passed    0.10 sec
        Start   4: TestIvlistDealloc.IVFPQ
  4/109 Test   #4: TestIvlistDealloc.IVFPQ .......................   Passed    0.18 sec
        Start   5: IVFPQ.codec
  5/109 Test   #5: IVFPQ.codec ...................................   Passed    0.63 sec
        Start   6: IVFPQ.accuracy
  6/109 Test   #6: IVFPQ.accuracy ................................   Passed    0.13 sec
        Start   7: TestLowLevelIVF.IVFFlatL2
  7/109 Test   #7: TestLowLevelIVF.IVFFlatL2 .....................   Passed    0.02 sec
        Start   8: TestLowLevelIVF.PCAIVFFlatL2
  8/109 Test   #8: TestLowLevelIVF.PCAIVFFlatL2 ..................   Passed    0.02 sec
        Start   9: TestLowLevelIVF.IVFFlatIP
  9/109 Test   #9: TestLowLevelIVF.IVFFlatIP .....................   Passed    0.02 sec
        Start  10: TestLowLevelIVF.IVFSQL2
 10/109 Test  #10: TestLowLevelIVF.IVFSQL2 .......................   Passed    0.02 sec
        Start  11: TestLowLevelIVF.IVFSQIP
 11/109 Test  #11: TestLowLevelIVF.IVFSQIP .......................   Passed    0.02 sec
        Start  12: TestLowLevelIVF.IVFPQL2
 12/109 Test  #12: TestLowLevelIVF.IVFPQL2 .......................   Passed    0.12 sec
        Start  13: TestLowLevelIVF.IVFPQIP
 13/109 Test  #13: TestLowLevelIVF.IVFPQIP .......................   Passed    0.11 sec
        Start  14: TestLowLevelIVF.IVFBinary
 14/109 Test  #14: TestLowLevelIVF.IVFBinary .....................   Passed    0.07 sec
        Start  15: TestLowLevelIVF.ThreadedSearch
 15/109 Test  #15: TestLowLevelIVF.ThreadedSearch ................   Passed    0.03 sec
        Start  16: MERGE.merge_flat_no_ids
 16/109 Test  #16: MERGE.merge_flat_no_ids .......................   Passed    0.01 sec
        Start  17: MERGE.merge_flat
 17/109 Test  #17: MERGE.merge_flat ..............................   Passed    0.01 sec
        Start  18: MERGE.merge_flat_vt
 18/109 Test  #18: MERGE.merge_flat_vt ...........................   Passed    0.01 sec
        Start  19: MERGE.merge_flat_ondisk
 19/109 Test  #19: MERGE.merge_flat_ondisk .......................   Passed    0.03 sec
        Start  20: MERGE.merge_flat_ondisk_2
 20/109 Test  #20: MERGE.merge_flat_ondisk_2 .....................   Passed    0.01 sec
        Start  21: Threading.openmp
 21/109 Test  #21: Threading.openmp ..............................   Passed    0.01 sec
        Start  22: ONDISK.make_invlists
 22/109 Test  #22: ONDISK.make_invlists ..........................   Passed    0.29 sec
        Start  23: ONDISK.test_add
 23/109 Test  #23: ONDISK.test_add ...............................   Passed    0.02 sec
        Start  24: ONDISK.make_invlists_threaded
 24/109 Test  #24: ONDISK.make_invlists_threaded .................   Passed    1.24 sec
        Start  25: test_search_centroid.IVFFlat
 25/109 Test  #25: test_search_centroid.IVFFlat ..................   Passed    0.03 sec
        Start  26: test_search_centroid.PCAIVFFlat
 26/109 Test  #26: test_search_centroid.PCAIVFFlat ...............   Passed    0.03 sec
        Start  27: test_search_and_return_centroids.IVFFlat
 27/109 Test  #27: test_search_and_return_centroids.IVFFlat ......   Passed    0.03 sec
        Start  28: test_search_and_return_centroids.PCAIVFFlat
 28/109 Test  #28: test_search_and_return_centroids.PCAIVFFlat ...   Passed    0.04 sec
        Start  29: TPO.IVFFlat
 29/109 Test  #29: TPO.IVFFlat ...................................   Passed    0.02 sec
        Start  30: TPO.IVFPQ
 30/109 Test  #30: TPO.IVFPQ .....................................   Passed    0.10 sec
        Start  31: TPO.IVFSQ
 31/109 Test  #31: TPO.IVFSQ .....................................   Passed    0.02 sec
        Start  32: TPO.IVFFlatPP
 32/109 Test  #32: TPO.IVFFlatPP .................................   Passed    0.02 sec
        Start  33: TPOB.IVF
 33/109 Test  #33: TPOB.IVF ......................................   Passed    0.01 sec
        Start  34: PQEncoderGeneric.encode
 34/109 Test  #34: PQEncoderGeneric.encode .......................   Passed    0.01 sec
        Start  35: PQEncoder8.encode
 35/109 Test  #35: PQEncoder8.encode .............................   Passed    0.01 sec
        Start  36: PQEncoder16.encode
 36/109 Test  #36: PQEncoder16.encode ............................   Passed    0.01 sec
        Start  37: SlidingWindow.IVFFlat
 37/109 Test  #37: SlidingWindow.IVFFlat .........................   Passed    0.80 sec
        Start  38: SlidingWindow.PCAIVFFlat
 38/109 Test  #38: SlidingWindow.PCAIVFFlat ......................   Passed    0.82 sec
        Start  39: SlidingInvlists.IVFFlat
 39/109 Test  #39: SlidingInvlists.IVFFlat .......................   Passed    0.78 sec
        Start  40: SlidingInvlists.PCAIVFFlat
 40/109 Test  #40: SlidingInvlists.PCAIVFFlat ....................   Passed    0.86 sec
        Start  41: ThreadedIndex.SingleException
 41/109 Test  #41: ThreadedIndex.SingleException .................   Passed    1.01 sec
        Start  42: ThreadedIndex.MultipleException
 42/109 Test  #42: ThreadedIndex.MultipleException ...............   Passed    1.03 sec
        Start  43: ThreadedIndex.TestReplica
 43/109 Test  #43: ThreadedIndex.TestReplica .....................   Passed    0.03 sec
        Start  44: ThreadedIndex.TestShards
 44/109 Test  #44: ThreadedIndex.TestShards ......................   Passed    0.02 sec
        Start  45: TRANS.IVFFlat
 45/109 Test  #45: TRANS.IVFFlat .................................   Passed    0.02 sec
        Start  46: TRANS.IVFFlatPreproc
 46/109 Test  #46: TRANS.IVFFlatPreproc ..........................   Passed    0.02 sec
        Start  47: TestGpuIndexFlat.IP_Float32
 47/109 Test  #47: TestGpuIndexFlat.IP_Float32 ...................   Passed    2.68 sec
        Start  48: TestGpuIndexFlat.L1_Float32
 48/109 Test  #48: TestGpuIndexFlat.L1_Float32 ...................   Passed    0.89 sec
        Start  49: TestGpuIndexFlat.Lp_Float32
 49/109 Test  #49: TestGpuIndexFlat.Lp_Float32 ...................   Passed    1.01 sec
        Start  50: TestGpuIndexFlat.L2_Float32
 50/109 Test  #50: TestGpuIndexFlat.L2_Float32 ...................   Passed    2.78 sec
        Start  51: TestGpuIndexFlat.L2_Float32_K1
 51/109 Test  #51: TestGpuIndexFlat.L2_Float32_K1 ................   Passed    0.74 sec
        Start  52: TestGpuIndexFlat.IP_Float16
 52/109 Test  #52: TestGpuIndexFlat.IP_Float16 ...................   Passed    2.21 sec
        Start  53: TestGpuIndexFlat.L2_Float16
 53/109 Test  #53: TestGpuIndexFlat.L2_Float16 ...................   Passed    2.13 sec
        Start  54: TestGpuIndexFlat.L2_Float16_K1
 54/109 Test  #54: TestGpuIndexFlat.L2_Float16_K1 ................   Passed    0.76 sec
        Start  55: TestGpuIndexFlat.L2_Tiling
 55/109 Test  #55: TestGpuIndexFlat.L2_Tiling ....................   Passed    1.06 sec
        Start  56: TestGpuIndexFlat.QueryEmpty
 56/109 Test  #56: TestGpuIndexFlat.QueryEmpty ...................   Passed    0.50 sec
        Start  57: TestGpuIndexFlat.CopyFrom
 57/109 Test  #57: TestGpuIndexFlat.CopyFrom .....................   Passed    0.52 sec
        Start  58: TestGpuIndexFlat.CopyTo
 58/109 Test  #58: TestGpuIndexFlat.CopyTo .......................   Passed    0.50 sec
        Start  59: TestGpuIndexFlat.UnifiedMemory
 59/109 Test  #59: TestGpuIndexFlat.UnifiedMemory ................   Passed    0.56 sec
        Start  60: TestGpuIndexIVFFlat.Float32_32_Add_L2
 60/109 Test  #60: TestGpuIndexIVFFlat.Float32_32_Add_L2 .........   Passed    0.66 sec
        Start  61: TestGpuIndexIVFFlat.Float32_32_Add_IP
 61/109 Test  #61: TestGpuIndexIVFFlat.Float32_32_Add_IP .........   Passed    0.66 sec
        Start  62: TestGpuIndexIVFFlat.Float16_32_Add_L2
 62/109 Test  #62: TestGpuIndexIVFFlat.Float16_32_Add_L2 .........   Passed    0.64 sec
        Start  63: TestGpuIndexIVFFlat.Float16_32_Add_IP
 63/109 Test  #63: TestGpuIndexIVFFlat.Float16_32_Add_IP .........   Passed    0.69 sec
        Start  64: TestGpuIndexIVFFlat.Float32_Query_L2
 64/109 Test  #64: TestGpuIndexIVFFlat.Float32_Query_L2 ..........   Passed    0.68 sec
        Start  65: TestGpuIndexIVFFlat.Float32_Query_IP
 65/109 Test  #65: TestGpuIndexIVFFlat.Float32_Query_IP ..........   Passed    0.69 sec
        Start  66: TestGpuIndexIVFFlat.Float16_32_Query_L2
 66/109 Test  #66: TestGpuIndexIVFFlat.Float16_32_Query_L2 .......   Passed    0.66 sec
        Start  67: TestGpuIndexIVFFlat.Float16_32_Query_IP
 67/109 Test  #67: TestGpuIndexIVFFlat.Float16_32_Query_IP .......   Passed    0.66 sec
        Start  68: TestGpuIndexIVFFlat.Float32_Query_L2_64
 68/109 Test  #68: TestGpuIndexIVFFlat.Float32_Query_L2_64 .......   Passed    0.67 sec
        Start  69: TestGpuIndexIVFFlat.Float32_Query_IP_64
 69/109 Test  #69: TestGpuIndexIVFFlat.Float32_Query_IP_64 .......   Passed    0.68 sec
        Start  70: TestGpuIndexIVFFlat.Float32_Query_L2_128
 70/109 Test  #70: TestGpuIndexIVFFlat.Float32_Query_L2_128 ......   Passed    0.63 sec
        Start  71: TestGpuIndexIVFFlat.Float32_Query_IP_128
 71/109 Test  #71: TestGpuIndexIVFFlat.Float32_Query_IP_128 ......   Passed    0.64 sec
        Start  72: TestGpuIndexIVFFlat.Float32_32_CopyTo
 72/109 Test  #72: TestGpuIndexIVFFlat.Float32_32_CopyTo .........   Passed    0.56 sec
        Start  73: TestGpuIndexIVFFlat.Float32_32_CopyFrom
 73/109 Test  #73: TestGpuIndexIVFFlat.Float32_32_CopyFrom .......   Passed    0.54 sec
        Start  74: TestGpuIndexIVFFlat.Float32_negative
 74/109 Test  #74: TestGpuIndexIVFFlat.Float32_negative ..........   Passed    0.55 sec
        Start  75: TestGpuIndexIVFFlat.QueryNaN
 75/109 Test  #75: TestGpuIndexIVFFlat.QueryNaN ..................   Passed    0.55 sec
        Start  76: TestGpuIndexIVFFlat.AddNaN
 76/109 Test  #76: TestGpuIndexIVFFlat.AddNaN ....................   Passed    0.55 sec
        Start  77: TestGpuIndexIVFFlat.UnifiedMemory
 77/109 Test  #77: TestGpuIndexIVFFlat.UnifiedMemory .............   Passed    0.59 sec
        Start  78: TestGpuIndexBinaryFlat.Test8
 78/109 Test  #78: TestGpuIndexBinaryFlat.Test8 ..................   Passed    1.17 sec
        Start  79: TestGpuIndexBinaryFlat.Test32
 79/109 Test  #79: TestGpuIndexBinaryFlat.Test32 .................   Passed    1.13 sec
        Start  80: TestGpuMemoryException.AddException
 80/109 Test  #80: TestGpuMemoryException.AddException ...........Child aborted***Exception:   4.50 sec
        Start  81: TestGpuIndexIVFPQ.Query_L2
 81/109 Test  #81: TestGpuIndexIVFPQ.Query_L2 ....................   Passed    0.89 sec
        Start  82: TestGpuIndexIVFPQ.Query_IP
 82/109 Test  #82: TestGpuIndexIVFPQ.Query_IP ....................   Passed    0.90 sec
        Start  83: TestGpuIndexIVFPQ.Float16Coarse
 83/109 Test  #83: TestGpuIndexIVFPQ.Float16Coarse ...............Child aborted***Exception:   4.62 sec
        Start  84: TestGpuIndexIVFPQ.Add_L2
 84/109 Test  #84: TestGpuIndexIVFPQ.Add_L2 ......................   Passed    1.01 sec
        Start  85: TestGpuIndexIVFPQ.Add_IP
 85/109 Test  #85: TestGpuIndexIVFPQ.Add_IP ......................   Passed    0.93 sec
        Start  86: TestGpuIndexIVFPQ.CopyTo
 86/109 Test  #86: TestGpuIndexIVFPQ.CopyTo ......................   Passed    0.73 sec
        Start  87: TestGpuIndexIVFPQ.CopyFrom
 87/109 Test  #87: TestGpuIndexIVFPQ.CopyFrom ....................   Passed    0.64 sec
        Start  88: TestGpuIndexIVFPQ.QueryNaN
 88/109 Test  #88: TestGpuIndexIVFPQ.QueryNaN ....................   Passed    0.70 sec
        Start  89: TestGpuIndexIVFPQ.AddNaN
 89/109 Test  #89: TestGpuIndexIVFPQ.AddNaN ......................   Passed    0.68 sec
        Start  90: TestGpuIndexIVFPQ.UnifiedMemory
 90/109 Test  #90: TestGpuIndexIVFPQ.UnifiedMemory ...............   Passed    1.01 sec
        Start  91: TestGpuDistance.Transposition_RR
 91/109 Test  #91: TestGpuDistance.Transposition_RR ..............   Passed    0.92 sec
        Start  92: TestGpuDistance.Transposition_RC
 92/109 Test  #92: TestGpuDistance.Transposition_RC ..............   Passed    0.66 sec
        Start  93: TestGpuDistance.Transposition_CR
 93/109 Test  #93: TestGpuDistance.Transposition_CR ..............   Passed    0.62 sec
        Start  94: TestGpuDistance.Transposition_CC
 94/109 Test  #94: TestGpuDistance.Transposition_CC ..............   Passed    0.62 sec
        Start  95: TestGpuDistance.L1
 95/109 Test  #95: TestGpuDistance.L1 ............................   Passed    0.68 sec
        Start  96: TestGpuDistance.L1_RC
 96/109 Test  #96: TestGpuDistance.L1_RC .........................   Passed    0.71 sec
        Start  97: TestGpuDistance.L1_CR
 97/109 Test  #97: TestGpuDistance.L1_CR .........................   Passed    0.73 sec
        Start  98: TestGpuDistance.L1_CC
 98/109 Test  #98: TestGpuDistance.L1_CC .........................   Passed    0.74 sec
        Start  99: TestGpuDistance.Linf
 99/109 Test  #99: TestGpuDistance.Linf ..........................   Passed    0.99 sec
        Start 100: TestGpuDistance.Lp
100/109 Test #100: TestGpuDistance.Lp ............................   Passed    1.94 sec
        Start 101: TestGpuDistance.Canberra
101/109 Test #101: TestGpuDistance.Canberra ......................   Passed    1.01 sec
        Start 102: TestGpuDistance.BrayCurtis
102/109 Test #102: TestGpuDistance.BrayCurtis ....................   Passed    0.74 sec
        Start 103: TestGpuDistance.JensenShannon
103/109 Test #103: TestGpuDistance.JensenShannon .................   Passed    3.09 sec
        Start 104: TestGpuSelect.test
104/109 Test #104: TestGpuSelect.test ............................   Passed    2.29 sec
        Start 105: TestGpuSelect.test1
105/109 Test #105: TestGpuSelect.test1 ...........................   Passed    1.32 sec
        Start 106: TestGpuSelect.testExact
106/109 Test #106: TestGpuSelect.testExact .......................   Passed    0.99 sec
        Start 107: TestGpuSelect.testWarp
107/109 Test #107: TestGpuSelect.testWarp ........................   Passed    2.19 sec
        Start 108: TestGpuSelect.test1Warp
108/109 Test #108: TestGpuSelect.test1Warp .......................   Passed    1.28 sec
        Start 109: TestGpuSelect.testExactWarp
109/109 Test #109: TestGpuSelect.testExactWarp ...................   Passed    0.94 sec

98% tests passed, 2 tests failed out of 109

Total Test time (real) =  77.94 sec

The following tests FAILED:
	 80 - TestGpuMemoryException.AddException (Child aborted)
	 83 - TestGpuIndexIVFPQ.Float16Coarse (Child aborted)
Errors while running CTest
```

Sadly, the tests only say, that the test was aborted and that is all. My C++ is rather rusty in order to investigate further.

**Comment by mdouze** [comment]
How did you get this nice test log?
The Float16Coarse (#83) is expected. 
The AddException is not AFAIK.

**Comment by otaj** [comment]
```
mkdir build
cd build
cmake .. -DFAISS_ENABLE_GPU=ON -DFAISS_ENABLE_PYTHON=ON -DCUDAToolkit_ROOT=/opt/cuda -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CUDA_ARCHITECTURES=\"75\" -DBUILD_TESTING=ON
make
make test
```

Could you make it so that the does not fail? gtest surely has to have some utility to expect abort

**Comment by wickedfoo** [comment]
Float16Coarse should be fixed now (8f6a019ecddaffff263ecb7e77451bdc2c187b50).

The AddException thing I haven't seen, could be related to running it on a 4 GB GPU. I'll investigate.

**Comment by otaj** [comment]
Can confirm the mentioned merge does fix Float16Coarse error. Sadly, the AddException is still present. I don't have an access to a larger GPU to test the hypothesis that it is related to small size of my GPU

**Comment by nylocx** [comment]
Hi, for me this also breaks on Arch Linux with the current master.
```
Start  80: TestGpuMemoryException.AddException
80/113 Test  #80: TestGpuMemoryException.AddException ...........Subprocess aborted***Exception:   2.01 sec
```

I also have a 4GB GPU (GeForce GTX 1050 Ti Mobile) would really be nice it this could be fixed.

**Comment by mdouze** [comment]
Does this test still fail?

**Comment by otaj** [comment]
@mdouze Yes

**Comment by nylocx** [comment]
For me too

**Comment by wickedfoo** [comment]
I have reproduced and figured out the AddException problem, it is a CUDA 11 thing (either a bug or a subtle change in the API that is not documented). Fix coming soon.

**Comment by wickedfoo** [comment]
hopefully fixed in https://github.com/facebookresearch/faiss/commit/43ce2c93a45fecf0449446c2bd949f2357a4ea1a

**Comment by otaj** [comment]
Hi, thank you, can confirm, that the issue is fixed in master now :)
