### ISSUE TITLE
GPU usage when using faiss

### ISSUE THREAD

**Issue by keithbyr** [facebookresearch/faiss#337]
Hey, I encountered one issue when using faiss to do image retrieval. I have a VGG model run on GPU with tensorflow as backend to fetch features. And initialized one faiss index for retrieval on GPU too.
When running the two parts on Nvidia M40 (24GB) at the same time. I met with _Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at utils/StackDeviceMemory.cpp:147_ Does it means that the GPU memory is not enough for this task ?
I listed the two parts as below, could you please help check this or any suggestion about this ? Thank you~
#######################VGG16##########################
from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto()
**config.gpu_options.per_process_gpu_memory_fraction = 0.3**
set_session(tf.Session(config=config))

input_shape = (224, 224, 3)
model = VGG16(weights='imagenet', input_shape=(input_shape[0], input_shape[1], input_shape[2]), pooling='max',
              include_top=False)
##########################Faiss##############################
d = 512
k = 5
nlist = 500
quantizer = faiss.IndexFlatIP(d)  # the other index
index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_INNER_PRODUCT)
res = faiss.StandardGpuResources()
index = faiss.index_cpu_to_gpu(res, 0, index)

**Comment by wickedfoo** [comment]
Two questions:

1. How much GPU memory does your TF code use without the index?
2. Do you keep the `res = faiss.StandardGpuResources()` around for the lifetime of the index? Unfortunately ref counting is not built into the Faiss C++ API, so you will have to ensure that this object will remain in scope.

Also, Faiss by default takes 18% of GPU memory as space to perform temporary work. As your GPU has 24 GB of memory, you could and should probably reduce this. We typically need a scratch space of 1 - 2 GB in size.

**Comment by keithbyr** [comment]
hi, thank you for your advise. For your question, I just tried 1. Without training index and don't use it as retrieval method, the TF use around 5G memory. 2. I set res = faiss.StandardGpuResources() at the very begining of the python file, right after the import section. I think they should be around the lifetime of the index.  BTW, I am running this on a public server and only around 12G memory can be used. I think I should try to reduce the Faiss memory.  Any indication how to reduce this ?

**Comment by mdouze** [comment]
No activity, closing.

**Comment by wickedfoo** [comment]
@jrounds I believe this issue was fixed in the python API (but not the C++ one), so you needn't worry about it.

**Comment by mdouze** [comment]
Yes, it was fixed in 1.4.0, see #573

**Comment by qingfengmingyue** [comment]
@wickedfoo Hi,I still have this problem: Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at utils/StackDeviceMemory.cpp:146

i hava 100 index share faiss.StandardGpuResources(),but when i search index use threading.Semaphore(1)  ensure only be used by a single CPU thread ,Sometimes this error occurs,could you please help check this or any suggestion about this ? Thank you~
